### ISSUE TITLE
WordPress SEO's GitHub repo isn't suitable for inclusion as a submodule

### ISSUE THREAD

**Issue by Japh** [Chassis/Supercharger#4]
So it seems that the GitHub repo for WordPress SEO is source that requires building before being published to the WordPress.org repository. This probably makes it unsuitable for use as a Supercharger submodule.

See [WordPress-SEO#2029](https://github.com/Yoast/wordpress-seo/issues/2029) for more info.

**Comment by BronsonQuick** [comment]
@Japh Dang. That's annoying :disappointed: I was going to to a workaround and use http://svn2github.com/ and sync it with the SVN repo for WordPress SEO but the author of that service has put that on hold for the moment. So I'll go with `git@github.com:wp-plugins/wordpress-seo.git` instead. How's that sound Sir?

**Comment by Japh** [comment]
@BronsonQuick That would do the trick, I reckon!

I hadn't realised that was maintained by Bluehost. Nice.

**Comment by BronsonQuick** [comment]
Sweet as :+1:
